import { Card } from './card';

export const MYTHICS: Card[] = [
    {id:90, name:"Agadeem, the Undercrypt", rarity:"M"},
    {id:336, name:"Agadeem, the Undercrypt", rarity:"M"},
    {id:90, name:"Agadeem's Awakening", rarity:"M"},
    {id:336, name:"Agadeem's Awakening", rarity:"M"},
    {id:178, name:"Ancient Greenwarden", rarity:"M"},
    {id:357, name:"Ancient Greenwarden", rarity:"M"},
    {id:2, name:"Angel of Destiny", rarity:"M"},
    {id:314, name:"Angel of Destiny", rarity:"M"},
    {id:179, name:"Ashaya, Soul of the Wild", rarity:"M"},
    {id:358, name:"Ashaya, Soul of the Wild", rarity:"M"},
    {id:98, name:"Drana, the Last Bloodchief", rarity:"M"},
    {id:338, name:"Drana, the Last Bloodchief", rarity:"M"},
    {id:12, name:"Emeria, Shattered Skyclave", rarity:"M"},
    {id:317, name:"Emeria, Shattered Skyclave", rarity:"M"},
    {id:12, name:"Emeria's Call", rarity:"M"},
    {id:317, name:"Emeria's Call", rarity:"M"},
    {id:244, name:"Forsaken Monument", rarity:"M"},
    {id:374, name:"Forsaken Monument", rarity:"M"},
    {id:63, name:"Jace, Mirror Mage", rarity:"M"},
    {id:281, name:"Jace, Mirror Mage", rarity:"M"},
    {id:147, name:"Leyline Tyrant", rarity:"M"},
    {id:348, name:"Leyline Tyrant", rarity:"M"},
    {id:245, name:"Lithoform Engine", rarity:"M"},
    {id:375, name:"Lithoform Engine", rarity:"M"},
    {id:193, name:"Lotus Cobra", rarity:"R"},
    {id:307, name:"Lotus Cobra", rarity:"R"},
    {id:150, name:"Moraug, Fury of Akoum", rarity:"M"},
    {id:300, name:"Moraug, Fury of Akoum", rarity:"M"},
    {id:230, name:"Nahiri, Heir of the Ancients", rarity:"M"},
    {id:282, name:"Nahiri, Heir of the Ancients", rarity:"M"},
    {id:231, name:"Nissa of Shadowed Boughs", rarity:"M"},
    {id:283, name:"Nissa of Shadowed Boughs", rarity:"M"},
    {id:232, name:"Omnath, Locus of Creation", rarity:"M"},
    {id:312, name:"Omnath, Locus of Creation", rarity:"M"},
    {id:122, name:"Scourge of the Skyclaves", rarity:"M"},
    {id:343, name:"Scourge of the Skyclaves", rarity:"M"},
    {id:76, name:"Sea Gate Restoration", rarity:"M"},
    {id:333, name:"Sea Gate Restoration", rarity:"M"},
    {id:77, name:"Sea Gate Stormcaller", rarity:"M"},
    {id:334, name:"Sea Gate Stormcaller", rarity:"M"},
    {id:76, name:"Sea Gate, Reborn", rarity:"M"},
    {id:333, name:"Sea Gate, Reborn", rarity:"M"},
    {id:161, name:"Shatterskull Smashing", rarity:"M"},
    {id:354, name:"Shatterskull Smashing", rarity:"M"},
    {id:161, name:"Shatterskull, the Hammer Pass", rarity:"M"},
    {id:354, name:"Shatterskull, the Hammer Pass", rarity:"M"},
    {id:44, name:"Tazri, Beacon of Unity", rarity:"M"},
    {id:324, name:"Tazri, Beacon of Unity", rarity:"M"},
    {id:215, name:"Turntimber Symbiosis", rarity:"M"},
    {id:364, name:"Turntimber Symbiosis", rarity:"M"},
    {id:215, name:"Turntimber, Serpentine Wood", rarity:"M"},
    {id:364, name:"Turntimber, Serpentine Wood", rarity:"M"},
];