import { Card } from './card';

export const RARES: Card[] = [
    {id:220, name:"Akiri, Fearless Voyager", rarity:"R"},
    {id:4, name:"Archon of Emeria", rarity:"R"},
    {id:5, name:"Archpriest of Iona", rarity:"R"},
    {id:258, name:"Boulderloft Pathway", rarity:"R"},
    {id:284, name:"Boulderloft Pathway", rarity:"R"},
    {id:258, name:"Branchloft Pathway", rarity:"R"},
    {id:284, name:"Branchloft Pathway", rarity:"R"},
    {id:259, name:"Brightclimb Pathway", rarity:"R"},
    {id:285, name:"Brightclimb Pathway", rarity:"R"},
    {id:49, name:"Charix, the Raging Isle", rarity:"R"},
    {id:260, name:"Clearwater Pathway", rarity:"R"},
    {id:286, name:"Clearwater Pathway", rarity:"R"},
    {id:53, name:"Confounding Conundrum", rarity:"R"},
    {id:54, name:"Coralhelm Chronicler", rarity:"R"},
    {id:95, name:"Coveted Prize", rarity:"R"},
    {id:261, name:"Cragcrown Pathway", rarity:"R"},
    {id:287, name:"Cragcrown Pathway", rarity:"R"},
    {id:183, name:"Cragplate Baloth", rarity:"R"},
    {id:262, name:"Crawling Barrens", rarity:"R"},
    {id:16, name:"Felidar Retreat", rarity:"R"},
    {id:292, name:"Felidar Retreat", rarity:"R"},
    {id:60, name:"Glasspool Mimic", rarity:"R"},
    {id:60, name:"Glasspool Shore", rarity:"R"},
    {id:223, name:"Grakmaw, Skyclave Ravager", rarity:"R"},
    {id:259, name:"Grimclimb Pathway", rarity:"R"},
    {id:285, name:"Grimclimb Pathway", rarity:"R"},
    {id:106, name:"Hagra Broodpit", rarity:"R"},
    {id:106, name:"Hagra Mauling", rarity:"R"},
    {id:186, name:"Inscription of Abundance", rarity:"R"},
    {id:61, name:"Inscription of Insight", rarity:"R"},
    {id:108, name:"Inscription of Ruin", rarity:"R"},
    {id:145, name:"Kargan Intimidator", rarity:"R"},
    {id:225, name:"Kaza, Roil Chaser", rarity:"R"},
    {id:189, name:"Kazandu Mammoth", rarity:"R"},
    {id:189, name:"Kazandu Valley", rarity:"R"},
    {id:264, name:"Lavaglide Pathway", rarity:"R"},
    {id:289, name:"Lavaglide Pathway", rarity:"R"},
    {id:23, name:"Legion Angel", rarity:"R"},
    {id:226, name:"Linvala, Shield of Sea Gate", rarity:"R"},
    {id:193, name:"Lotus Cobra", rarity:"R"},
    {id:24, name:"Luminarch Aspirant", rarity:"R"},
    {id:67, name:"Maddening Cacophony", rarity:"R"},
    {id:148, name:"Magmatic Channeler", rarity:"R"},
    {id:68, name:"Master of Winds", rarity:"R"},
    {id:27, name:"Maul of the Skyclaves", rarity:"R"},
    {id:260, name:"Murkwater Pathway", rarity:"R"},
    {id:286, name:"Murkwater Pathway", rarity:"R"},
    {id:246, name:"Myriad Construct", rarity:"R"},
    {id:151, name:"Nahiri's Lithoforming", rarity:"R"},
    {id:263, name:"Needleverge Pathway", rarity:"R"},
    {id:288, name:"Needleverge Pathway", rarity:"R"},
    {id:71, name:"Negate", rarity:"R"},
    {id:115, name:"Nighthawk Scavenger", rarity:"R"},
    {id:72, name:"Nimble Trapfinder", rarity:"R"},
    {id:118, name:"Nullpriest of Oblivion", rarity:"R"},
    {id:30, name:"Ondu Inversion", rarity:"R"},
    {id:30, name:"Ondu Skyruins", rarity:"R"},
    {id:233, name:"Orah, Skyclave Hierophant", rarity:"R"},
    {id:198, name:"Oran-Rief Ooze", rarity:"R"},
    {id:234, name:"Phylath, World Sculptor", rarity:"R"},
    {id:263, name:"Pillarverge Pathway", rarity:"R"},
    {id:288, name:"Pillarverge Pathway", rarity:"R"},
    {id:153, name:"Relic Robber", rarity:"R"},
    {id:264, name:"Riverglide Pathway", rarity:"R"},
    {id:289, name:"Riverglide Pathway", rarity:"R"},
    {id:156, name:"Roiling Vortex", rarity:"R"},
    {id:203, name:"Scute Swarm", rarity:"R"},
    {id:124, name:"Shadows' Verdict", rarity:"R"},
    {id:159, name:"Shatterskull Charger", rarity:"R"},
    {id:39, name:"Skyclave Apparition", rarity:"R"},
    {id:252, name:"Skyclave Relic", rarity:"R"},
    {id:125, name:"Skyclave Shade", rarity:"R"},
    {id:298, name:"Skyclave Shade", rarity:"R"},
    {id:127, name:"Soul Shatter", rarity:"R"},
    {id:41, name:"Squad Commander", rarity:"R"},
    {id:207, name:"Swarm Shambler", rarity:"R"},
    {id:129, name:"Taborax, Hope's Demise", rarity:"R"},
    {id:209, name:"Tajuru Paragon", rarity:"R"},
    {id:85, name:"Thieving Skydiver", rarity:"R"},
    {id:265, name:"Throne of Makindi", rarity:"R"},
    {id:261, name:"Timbercrown Pathway", rarity:"R"},
    {id:287, name:"Timbercrown Pathway", rarity:"R"},
    {id:174, name:"Valakut Awakening", rarity:"R"},
    {id:175, name:"Valakut Exploration", rarity:"R"},
    {id:174, name:"Valakut Stoneforge", rarity:"R"},
    {id:239, name:"Verazol, the Split Current", rarity:"R"},
    {id:176, name:"Wayward Guide-Beast", rarity:"R"},
    {id:240, name:"Yasharn, Implacable Earth", rarity:"R"},
    {id:241, name:"Zagras, Thief of Heartbeats", rarity:"R"},
    {id:242, name:"Zareth San, the Trickster", rarity:"R"},
];