import { Card } from './card';

export const UNCOMMONS: Card[] = [
    {id:89, name:"Acquisitions Expert", rarity:"Uncommon"},
    {id:134, name:"Akoum Teeth", rarity:"Uncommon"},
    {id:134, name:"Akoum Warrior", rarity:"Uncommon"},
    {id:1, name:"Allied Assault", rarity:"Uncommon"},
    {id:6, name:"Attended Healer", rarity:"Uncommon"},
    {id:180, name:"Bala Ged Recovery", rarity:"Uncommon"},
    {id:180, name:"Bala Ged Sanctuary", rarity:"Uncommon"},
    {id:257, name:"Base Camp", rarity:"Uncommon"},
    {id:46, name:"Beyeen Coast", rarity:"Uncommon"},
    {id:46, name:"Beyeen Veil", rarity:"Uncommon"},
    {id:91, name:"Blackbloom Bog", rarity:"Uncommon"},
    {id:91, name:"Blackbloom Rogue", rarity:"Uncommon"},
    {id:94, name:"Bloodchief's Thirst", rarity:"Uncommon"},
    {id:221, name:"Brushfire Elemental", rarity:"Uncommon"},
    {id:311, name:"Brushfire Elemental", rarity:"Uncommon"},
    {id:7, name:"Canyon Jerboa", rarity:"Uncommon"},
    {id:290, name:"Canyon Jerboa", rarity:"Uncommon"},
    {id:136, name:"Cinderclasm", rarity:"Uncommon"},
    {id:222, name:"Cleric of Life's Bond", rarity:"Uncommon"},
    {id:52, name:"Concerted Defense", rarity:"Uncommon"},
    {id:97, name:"Demon's Disciple", rarity:"Uncommon"},
    {id:11, name:"Emeria Captain", rarity:"Uncommon"},
    {id:15, name:"Fearless Fledgling", rarity:"Uncommon"},
    {id:291, name:"Fearless Fledgling", rarity:"Uncommon"},
    {id:139, name:"Fireblade Charger", rarity:"Uncommon"},
    {id:141, name:"Goma Fada Vanguard", rarity:"Uncommon"},
    {id:143, name:"Grotag Night-Runner", rarity:"Uncommon"},
    {id:187, name:"Iridescent Hornbeetle", rarity:"Uncommon"},
    {id:17, name:"Journey to Oblivion", rarity:"Uncommon"},
    {id:64, name:"Jwari Disruption", rarity:"Uncommon"},
    {id:64, name:"Jwari Ruins", rarity:"Uncommon"},
    {id:19, name:"Kabira Plateau", rarity:"Uncommon"},
    {id:19, name:"Kabira Takedown", rarity:"Uncommon"},
    {id:224, name:"Kargan Warleader", rarity:"Uncommon"},
    {id:146, name:"Kazuul's Cliffs", rarity:"Uncommon"},
    {id:146, name:"Kazuul's Fury", rarity:"Uncommon"},
    {id:192, name:"Khalni Ambush", rarity:"Uncommon"},
    {id:192, name:"Khalni Territory", rarity:"Uncommon"},
    {id:20, name:"Kitesail Cleric", rarity:"Uncommon"},
    {id:21, name:"Kor Blademaster", rarity:"Uncommon"},
    {id:109, name:"Lithoform Blight", rarity:"Uncommon"},
    {id:66, name:"Lullmage's Domination", rarity:"Uncommon"},
    {id:227, name:"Lullmage's Familiar", rarity:"Uncommon"},
    {id:26, name:"Makindi Mesas", rarity:"Uncommon"},
    {id:26, name:"Makindi Stampede", rarity:"Uncommon"},
    {id:111, name:"Malakir Mire", rarity:"Uncommon"},
    {id:111, name:"Malakir Rebirth", rarity:"Uncommon"},
    {id:69, name:"Merfolk Falconer", rarity:"Uncommon"},
    {id:70, name:"Merfolk Windrobber", rarity:"Uncommon"},
    {id:113, name:"Mind Carver", rarity:"Uncommon"},
    {id:228, name:"Moss-Pit Skeleton", rarity:"Uncommon"},
    {id:229, name:"Murasa Rootgrazer", rarity:"Uncommon"},
    {id:196, name:"Murasa Sproutling", rarity:"Uncommon"},
    {id:31, name:"Paired Tactician", rarity:"Uncommon"},
    {id:120, name:"Pelakka Caverns", rarity:"Uncommon"},
    {id:120, name:"Pelakka Predation", rarity:"Uncommon"},
    {id:235, name:"Ravager's Mace", rarity:"Uncommon"},
    {id:247, name:"Relic Amulet", rarity:"Uncommon"},
    {id:248, name:"Relic Axe", rarity:"Uncommon"},
    {id:249, name:"Relic Golem", rarity:"Uncommon"},
    {id:250, name:"Relic Vial", rarity:"Uncommon"},
    {id:154, name:"Rockslide Sorcerer", rarity:"Uncommon"},
    {id:201, name:"Roiling Regrowth", rarity:"Uncommon"},
    {id:74, name:"Roost of Drakes", rarity:"Uncommon"},
    {id:75, name:"Ruin Crab", rarity:"Uncommon"},
    {id:295, name:"Ruin Crab", rarity:"Uncommon"},
    {id:121, name:"Scion of the Swarm", rarity:"Uncommon"},
    {id:37, name:"Sejiri Glacier", rarity:"Uncommon"},
    {id:37, name:"Sejiri Shelter", rarity:"Uncommon"},
    {id:123, name:"Shadow Stinger", rarity:"Uncommon"},
    {id:160, name:"Shatterskull Minotaur", rarity:"Uncommon"},
    {id:80, name:"Silundi Isle", rarity:"Uncommon"},
    {id:80, name:"Silundi Vision", rarity:"Uncommon"},
    {id:40, name:"Skyclave Basilica", rarity:"Uncommon"},
    {id:40, name:"Skyclave Cleric", rarity:"Uncommon"},
    {id:163, name:"Skyclave Geopede", rarity:"Uncommon"},
    {id:301, name:"Skyclave Geopede", rarity:"Uncommon"},
    {id:204, name:"Skyclave Pick-Axe", rarity:"Uncommon"},
    {id:309, name:"Skyclave Pick-Axe", rarity:"Uncommon"},
    {id:81, name:"Skyclave Plunder", rarity:"Uncommon"},
    {id:126, name:"Skyclave Shadowcat", rarity:"Uncommon"},
    {id:236, name:"Soaring Thought-Thief", rarity:"Uncommon"},
    {id:165, name:"Song-Mad Ruins", rarity:"Uncommon"},
    {id:165, name:"Song-Mad Treachery", rarity:"Uncommon"},
    {id:166, name:"Spikefield Cave", rarity:"Uncommon"},
    {id:166, name:"Spikefield Hazard", rarity:"Uncommon"},
    {id:237, name:"Spoils of Adventure", rarity:"Uncommon"},
    {id:205, name:"Springmantle Cleric", rarity:"Uncommon"},
    {id:83, name:"Sure-Footed Infiltrator", rarity:"Uncommon"},
    {id:211, name:"Tangled Florahedron", rarity:"Uncommon"},
    {id:211, name:"Tangled Vale", rarity:"Uncommon"},
    {id:212, name:"Taunting Arbormage", rarity:"Uncommon"},
    {id:170, name:"Thundering Rebuke", rarity:"Uncommon"},
    {id:171, name:"Thundering Sparkmage", rarity:"Uncommon"},
    {id:130, name:"Thwart the Grave", rarity:"Uncommon"},
    {id:238, name:"Umara Mystic", rarity:"Uncommon"},
    {id:86, name:"Umara Skyfalls", rarity:"Uncommon"},
    {id:86, name:"Umara Wizard", rarity:"Uncommon"},
    {id:216, name:"Vastwood Fortification", rarity:"Uncommon"},
    {id:217, name:"Vastwood Surge", rarity:"Uncommon"},
    {id:216, name:"Vastwood Thicket", rarity:"Uncommon"},
    {id:218, name:"Veteran Adventurer", rarity:"Uncommon"},
    {id:219, name:"Vine Gecko", rarity:"Uncommon"},
    {id:87, name:"Windrider Wizard", rarity:"Uncommon"},
    {id:132, name:"Zof Bloodbog", rarity:"Uncommon"},
    {id:132, name:"Zof Consumption", rarity:"Uncommon"},
];