import { Card } from './card';

export const MYTHICS: Card[] = [
    {id:90, name:"Agadeem, the Undercrypt", rarity:"Mythic"},
    {id:178, name:"Ancient Greenwarden", rarity:"Mythic"},
    {id:2, name:"Angel of Destiny", rarity:"Mythic"},
    {id:179, name:"Ashaya, Soul of the Wild", rarity:"Mythic"},
    {id:98, name:"Drana, the Last Bloodchief", rarity:"Mythic"},
    {id:12, name:"Emeria, Shattered Skyclave", rarity:"Mythic"},
    {id:12, name:"Emeria's Call", rarity:"Mythic"},
    {id:244, name:"Forsaken Monument", rarity:"Mythic"},
    {id:63, name:"Jace, Mirror Mage", rarity:"Mythic"},
    {id:147, name:"Leyline Tyrant", rarity:"Mythic"},
    {id:245, name:"Lithoform Engine", rarity:"Mythic"},
    {id:150, name:"Moraug, Fury of Akoum", rarity:"Mythic"},
    {id:230, name:"Nahiri, Heir of the Ancients", rarity:"Mythic"},
    {id:231, name:"Nissa of Shadowed Boughs", rarity:"Mythic"},
    {id:232, name:"Omnath, Locus of Creation", rarity:"Mythic"},
    {id:122, name:"Scourge of the Skyclaves", rarity:"Mythic"},
    {id:76, name:"Sea Gate Restoration", rarity:"Mythic"},
    {id:77, name:"Sea Gate Stormcaller", rarity:"Mythic"},
    {id:76, name:"Sea Gate, Reborn", rarity:"Mythic"},
    {id:161, name:"Shatterskull Smashing", rarity:"Mythic"},
    {id:161, name:"Shatterskull, the Hammer Pass", rarity:"Mythic"},
    {id:44, name:"Tazri, Beacon of Unity", rarity:"Mythic"},
    {id:215, name:"Turntimber Symbiosis", rarity:"Mythic"},
    {id:215, name:"Turntimber, Serpentine Wood", rarity:"Mythic"},
];