import { Card } from './card';

export const COMMONS: Card[] = [
    {id:177, name:"Adventure Awaits", rarity:"Common"},
    {id:133, name:"Akoum Hellhound", rarity:"Common"},
    {id:299, name:"Akoum Hellhound", rarity:"Common"},
    {id:3, name:"Angelheart Protector", rarity:"Common"},
    {id:45, name:"Anticognition", rarity:"Common"},
    {id:135, name:"Ardent Electromancer", rarity:"Common"},
    {id:92, name:"Blood Beckoning", rarity:"Common"},
    {id:93, name:"Blood Price", rarity:"Common"},
    {id:181, name:"Broken Wings", rarity:"Common"},
    {id:47, name:"Bubble Snare", rarity:"Common"},
    {id:182, name:"Canopy Baloth", rarity:"Common"},
    {id:304, name:"Canopy Baloth", rarity:"Common"},
    {id:48, name:"Cascade Seer", rarity:"Common"},
    {id:50, name:"Chilling Trap", rarity:"Common"},
    {id:137, name:"Cleansing Wildfire", rarity:"Common"},
    {id:51, name:"Cleric of Chill Depths", rarity:"Common"},
    {id:243, name:"Cliffhaven Kitesail", rarity:"Common"},
    {id:8, name:"Cliffhaven Sell-Sword", rarity:"Common"},
    {id:55, name:"Cunning Geysermage", rarity:"Common"},
    {id:184, name:"Dauntless Survivor", rarity:"Common"},
    {id:9, name:"Dauntless Unity", rarity:"Common"},
    {id:96, name:"Deadly Alliance", rarity:"Common"},
    {id:56, name:"Deliberate", rarity:"Common"},
    {id:10, name:"Disenchant", rarity:"Common"},
    {id:99, name:"Drana's Silencer", rarity:"Common"},
    {id:100, name:"Dreadwurm", rarity:"Common"},
    {id:297, name:"Dreadwurm", rarity:"Common"},
    {id:138, name:"Expedition Champion", rarity:"Common"},
    {id:57, name:"Expedition Diviner", rarity:"Common"},
    {id:13, name:"Expedition Healer", rarity:"Common"},
    {id:101, name:"Expedition Skulker", rarity:"Common"},
    {id:14, name:"Farsight Adept", rarity:"Common"},
    {id:102, name:"Feed the Swarm", rarity:"Common"},
    {id:58, name:"Field Research", rarity:"Common"},
    {id:140, name:"Fissure Wizard", rarity:"Common"},
    {id:103, name:"Ghastly Gloomhunter", rarity:"Common"},
    {id:59, name:"Glacial Grasp", rarity:"Common"},
    {id:185, name:"Gnarlid Colony", rarity:"Common"},
    {id:142, name:"Grotag Bug-Catcher", rarity:"Common"},
    {id:104, name:"Guul Draz Mucklord", rarity:"Common"},
    {id:105, name:"Hagra Constrictor", rarity:"Common"},
    {id:107, name:"Highborn Vampire", rarity:"Common"},
    {id:144, name:"Inordinate Rage", rarity:"Common"},
    {id:62, name:"Into the Roil", rarity:"Common"},
    {id:188, name:"Joraga Visionary", rarity:"Common"},
    {id:18, name:"Kabira Outrider", rarity:"Common"},
    {id:190, name:"Kazandu Nectarpot", rarity:"Common"},
    {id:306, name:"Kazandu Nectarpot", rarity:"Common"},
    {id:191, name:"Kazandu Stomper", rarity:"Common"},
    {id:22, name:"Kor Celebrant", rarity:"Common"},
    {id:65, name:"Living Tempest", rarity:"Common"},
    {id:25, name:"Makindi Ox", rarity:"Common"},
    {id:293, name:"Makindi Ox", rarity:"Common"},
    {id:110, name:"Malakir Blood-Priest", rarity:"Common"},
    {id:112, name:"Marauding Blight-Priest", rarity:"Common"},
    {id:28, name:"Mesa Lynx", rarity:"Common"},
    {id:194, name:"Might of Murasa", rarity:"Common"},
    {id:114, name:"Mind Drain", rarity:"Common"},
    {id:149, name:"Molten Blast", rarity:"Common"},
    {id:195, name:"Murasa Brute", rarity:"Common"},
    {id:29, name:"Nahiri's Binding", rarity:"Common"},
    {id:71, name:"Negate", rarity:"Common"},
    {id:116, name:"Nimana Skitter-Sneak", rarity:"Common"},
    {id:117, name:"Nimana Skydancer", rarity:"Common"},
    {id:197, name:"Nissa's Zendikon", rarity:"Common"},
    {id:119, name:"Oblivion's Hunger", rarity:"Common"},
    {id:32, name:"Practiced Tactics", rarity:"Common"},
    {id:33, name:"Pressure Point", rarity:"Common"},
    {id:34, name:"Prowling Felidar", rarity:"Common"},
    {id:294, name:"Prowling Felidar", rarity:"Common"},
    {id:152, name:"Pyroclastic Hellion", rarity:"Common"},
    {id:199, name:"Rabid Bite", rarity:"Common"},
    {id:200, name:"Reclaim the Wastes", rarity:"Common"},
    {id:35, name:"Resolute Strike", rarity:"Common"},
    {id:73, name:"Risen Riptide", rarity:"Common"},
    {id:155, name:"Roil Eruption", rarity:"Common"},
    {id:202, name:"Scale the Heights", rarity:"Common"},
    {id:157, name:"Scavenged Blade", rarity:"Common"},
    {id:158, name:"Scorch Rider", rarity:"Common"},
    {id:36, name:"Sea Gate Banneret", rarity:"Common"},
    {id:251, name:"Sea Gate Colossus", rarity:"Common"},
    {id:78, name:"Seafloor Stalker", rarity:"Common"},
    {id:79, name:"Shell Shield", rarity:"Common"},
    {id:38, name:"Shepherd of Heroes", rarity:"Common"},
    {id:162, name:"Sizzling Barrage", rarity:"Common"},
    {id:253, name:"Skyclave Sentinel", rarity:"Common"},
    {id:82, name:"Skyclave Squid", rarity:"Common"},
    {id:296, name:"Skyclave Squid", rarity:"Common"},
    {id:42, name:"Smite the Monstrous", rarity:"Common"},
    {id:164, name:"Sneaking Guide", rarity:"Common"},
    {id:254, name:"Spare Supplies", rarity:"Common"},
    {id:167, name:"Spitfire Lagac", rarity:"Common"},
    {id:302, name:"Spitfire Lagac", rarity:"Common"},
    {id:255, name:"Stonework Packbeast", rarity:"Common"},
    {id:206, name:"Strength of Solidarity", rarity:"Common"},
    {id:128, name:"Subtle Strike", rarity:"Common"},
    {id:168, name:"Synchronized Spellcraft", rarity:"Common"},
    {id:208, name:"Tajuru Blightblade", rarity:"Common"},
    {id:210, name:"Tajuru Snarecaster", rarity:"Common"},
    {id:43, name:"Tazeem Raptor", rarity:"Common"},
    {id:84, name:"Tazeem Roilmage", rarity:"Common"},
    {id:169, name:"Teeterpeak Ambusher", rarity:"Common"},
    {id:213, name:"Territorial Scythecat", rarity:"Common"},
    {id:310, name:"Territorial Scythecat", rarity:"Common"},
    {id:172, name:"Tormenting Voice", rarity:"Common"},
    {id:173, name:"Tuktuk Rubblefort", rarity:"Common"},
    {id:214, name:"Turntimber Ascetic", rarity:"Common"},
    {id:256, name:"Utility Knife", rarity:"Common"},
    {id:131, name:"Vanquish the Weak", rarity:"Common"},
    {id:88, name:"Zulaport Duelist", rarity:"Common"},
];

